site_name: Devops Docs
site_description: A DevOps knowledgebase created by Scott McCarthy
site_author: Scott McCarthy
site_url: https://niodus.github.io/devops-docs/
repo_url: https://github.com/Niodus/devops-docs
use_directory_urls: false
theme:
  name: material
  icon:
    logo: logo

  # Additional features used
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.tracking
    - navigation.top
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes

# Necessary for search to work properly
# include_search_page: false
# search_index_only: true

### --- START OF EXTENSIONS & PLUGIN SECTION --- ###
markdown_extensions:
  - toc:
      permalink: true

  # Used for tasklists
  # - def_list

  # used for adding checkboxes to pages
  # - pymdownx.tasklist:
  #    custom_checkbox: true

  # Used to allow for customisation of tables
  #- tables

  # used for Images and adding inline captions
  #- attr_list
  #- md_in_html

  # Used for glossary page and adding abbrviations
  #- pymdownx.snippets:
  #    auto_append:
  #        - includes/abbreviations.md

plugins:
  # plugin used to add search capability to site
  - search
  - glightbox

  # allow clickable sections that lead to an index page - https://oprypin.github.io/mkdocs-section-index/
  - section-index
  - literate-nav
#    - literate-nav:
#        nav_file: nav-menu.md

### --- START OF NAVIGATION SECTION -- ###

nav:
    - Home: index.md
    - The Basics:
        - the-basics.md
        - the-basics/how-to-get-started.md
        - the-basics/devops-vs-sre.md
        - the-basics/calms.md
        - the-basics/glossary.md
    - Best Practices:
        - best-practices.md
        - Continuous Planning:
            - best-practices/continuous-planning.md
            - Agile Development:
                - best-practices/continuous-planning/agile-development.md
                - best-practices/continuous-planning/agile-development/backlog-management.md
                - best-practices/continuous-planning/agile-development/collaboration.md
                - best-practices/continuous-planning/agile-development/delivery-plan.md
                - best-practices/continuous-planning/agile-development/retrospectives.md
                - best-practices/continuous-planning/agile-development/scrum-of-scrums.md
                - Sprint Planning:
                    - best-practices/continuous-planning/agile-development/sprint-planning.md
                    - best-practices/continuous-planning/agile-development/sprint-planning/estimation.md
                    - best-practices/continuous-planning/agile-development/sprint-planning/sprint-structure.md
                - Standups:
                    - best-practices/continuous-planning/agile-development/stand-ups.md
                    - best-practices/continuous-planning/agile-development/stand-ups/social-question.md
                - Team Agreements:
                    - best-practices/continuous-planning/agile-development/team-agreements.md
                    - best-practices/continuous-planning/agile-development/team-agreements/definition-of-done.md
                    - best-practices/continuous-planning/agile-development/team-agreements/definition-of-ready.md
                    - best-practices/continuous-planning/agile-development/team-agreements/team-charter.md
                    - best-practices/continuous-planning/agile-development/team-agreements/team-engagements.md
                    - best-practices/continuous-planning/agile-development/team-agreements/working-agreements.md
            - Design Reviews:
                - best-practices/continuous-planning/design-reviews.md
                - best-practices/continuous-planning/design-reviews/non-functional-requirements.md
                - Design Patterns:
                    - best-practices/continuous-planning/design-reviews/design-patterns.md
                    - best-practices/continuous-planning/design-reviews/design-patterns/data-heavy-design-guidance.md
                    - best-practices/continuous-planning/design-reviews/design-patterns/object-oriented-design-reference.md
                    - best-practices/continuous-planning/design-reviews/design-patterns/distributed-system-design-reference.md
                    - best-practices/continuous-planning/design-reviews/design-patterns/rest-api-design-guidance.md

        - Continuous Integration:
            - best-practices/continuous-integration.md
  #          - test:
  #              - test-file.md
        - Continuous Delivery:
            - best-practices/continuous-delivery.md
    #        - Infrastructure as Code:
    #        - Monitoring and Logging:
    #        - Communication and Collaboration:
    - Tools:
        - tools.md
        - Git SCM:
            - tools/git/git-cheatsheet.md
    - Learning:
        - learning.md
        - learning/devops-sfia.md
    - About: about.md
### END OF FILE ###
