### SITE BASE CONFIG ###

# Default values, taken from mkdocs_theme.yml
site_name:  Devops Docs
site_url:   https://niodus.github.io/devops-docs/
language: en
font:
    text: Roboto
    code: Roboto Mono
    favicon: assets/favicon.png
icon:
    logo: logo
theme:
    name: material
#    custom_dir: overrides   # Not currently used

    features:
#    - navigation.instant
#    - navigation.tracking
    - navigation.top
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - navigation.indexes

# Necessary for search to work properly
include_search_page: false
search_index_only: true

### START OF EXTENSIONS SECTION ###

markdown_extensions:
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md


#### START OF NAVIGATION SECTION ###

nav:
    - Home:                                 index.md 

    - The Basics: 
        -                                   devops-basics/what-is-devops.md
        -                                   devops-basics/how-to-get-started.md
        -                                   devops-basics/devops-vs-sre.md
        -                                   devops-basics/glossary.md

    - Best Practices:
        -                                   devops-practices/practice-overview.md
        - Continuous Planning: 
            - What is Continuous Planning:  devops-practices/continuous-planning/whatis-continuous-planning.md
        - Agile Development: 
            - What is is Agile:             devops-practices/continuous-planning/agile-development/whatis-agile.md
            - Backlog Management:           devops-practices/continuous-planning/agile-development/backlog-management.md

    - Tools:
         -                                  devops-tools/tools-overview.md

    - Learning:
        -                                   devops-learning/learning-overview.md

    - About:                                about.md



    #### END OF NAVIGATION SECTION ###