name: integration 
on:
  push:
    branches:
      - master 
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install mkdocs-material
      - run: pip install pymdown-extensions
      - run: pip install mkdocs-glightbox
      - run: pip install mkdocs-section-index
      - run: pip install mkdocs-literate-nav
      - run: mkdocs gh-deploy --force
